version: "3.9"
services:
  backend:
    build:
      context: ./apps/backend
    image: public.ecr.aws/t6b6n7l9/personal-site-backend:latest
    container_name: site-backend-strapi
    restart: always
    volumes:
      - strapi-sqlite-volume:/usr/app/.tmp
    ports:
      - "1337:1337"
  frontend:
    build:
      context: ./apps/frontend
    image: public.ecr.aws/t6b6n7l9/personal-site-frontend:latest
    container_name: site-frontend-sveltekit
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  strapi-sqlite-volume: