version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.14.0
    resource_class: medium
    description: build docker
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --prefer-offline --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - restore_cache:
          name: Restore turborepo build cache
          keys:
            - turborepo
      - run:
          name: build with turborepo
          command: yarn run build
      - save_cache:
          name: Save turborepo build cache
          key: turborepo
          paths:
            - ./turbocache
